name: Update Huggingface Space

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Gradio
      run: python -m pip install gradio

    - name: Log in to Hugging Face
      run: |
        git config --global credential.helper store
        huggingface-cli login --token ${{ secrets.hf_token }} --add-to-git-credential
  
    - name: Deploy to Spaces
      run: gradio deploy
